stages:
  - deploy

deploy_app:
  stage: deploy
  script:
    - echo "Marking safe directory for Git..."
    - git config --global --add safe.directory 'C:/Users/FIT/ai_proj/ai_generative_question_v2'
    - echo "Pulling latest changes..."
    - cd 'C:\Users\FIT\ai_proj\ai_generative_question_v2\'
    - git pull origin neo4j_version
    - echo "Running FastAPI app with Uvicorn..."
    - cd 'C:\Users\FIT\ai_proj\ai_generative_question_v2\app'
    - uvicorn main:app --host 192.168.100.3 --port 8002
