variables:
  REPOSITORY: "10.70.0.28:4321/ai-generative"
  TAG_COMMIT: "$REPOSITORY/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA"
  TAG_LATEST: "$REPOSITORY/$CI_PROJECT_NAME:latest"
  DOCKERUSER: "admin"
  DOCKERPASSWORD: "falah0918"
  GIT_DEPTH: "0"
  FLUX_HTTPS_URL: "https://wussh:$GIT_TOKEN@github.com/wussh/flux-new.git"
  SONAR_TOKEN: "sqp_c603f9ae5f2214410bf0da36c4f0e08501bda0b9"
  SONAR_HOST_URL: "http://10.70.0.28:9000"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  SSHUSER: "softwaredev"
  SSHPASS: "Falah0918"
  SSHSERVER: "192.168.100.3"
  BASE_DIR: "/home/softwaredev/staging/ai-generative-question/app"
  BRANCH: "$CI_COMMIT_REF_NAME"
  DOCKER_COMMAND: "docker compose up -d"

stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: 10.70.0.28:4321/library/kaniko-executor:v1.23.2-debug
    entrypoint: [""]
  variables:
    DOCKER_CONFIG: "/kaniko/.docker/"
  cache:
    key: "${CI_COMMIT_REF_SLUG}-kaniko"
    paths:
      - /cache
    policy: pull-push
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REPOSITORY\":{\"username\":\"$DOCKERUSER\",\"password\":\"$DOCKERPASSWORD\",\"auth\":\"$(echo -n "$DOCKERUSER:$DOCKERPASSWORD" | base64)\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/app"
      --dockerfile "${CI_PROJECT_DIR}/app/Dockerfile"
      --destination "${TAG_COMMIT}"
      --destination "${TAG_LATEST}"
      --insecure-registry
      --skip-tls-verify
      --skip-tls-verify-pull
      --skip-tls-verify-registry
      --cache=true
      --snapshot-mode=redo
      --use-new-run
      --cache-dir=/cache
  only:
    - neo4j_version

deploy_app:
  stage: deploy
  image: ringcentral/sshpass:latest
  before_script:
    - echo "Starting deployment..."
  script:
    - sshpass -e ssh -o StrictHostKeyChecking=no "$SSHUSER@$SSHSERVER" "
        cd $BASE_DIR &&
        git fetch origin $BRANCH &&
        git reset --hard origin/$BRANCH &&
        git pull &&
        $DOCKER_COMMAND &&
        echo 'Deployment of ai generative question staging completed.'
      "
  only:
    - neo4j_version