services:
  app:
    image: registry.falahtech.com/ai-generative/ai-generative-question:latest
    pull_policy: always
    restart: always
    container_name: ai-generative-question
    ports:
      - "8002:8002"
