services:
  app:
    image: registry.falahtech.com/ai-generative/ai-generative-question:latest
    pull_policy: always
    restart: always
    container_name: ai-generative-question
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      - OLLAMA_HOST=http://10.11.127.202:11434
      - OLLAMA_MODEL=llama3.2:latest
      - NEO4J_URL=bolt://10.11.127.202:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=admin.admin
      - UPLOAD_DIR=uploads
      - ENGLISH_DIR=uploads/english
      - INDONESIAN_DIR=uploads/indonesian